---
- name: Install Docker on EC2 target inance
  hosts: localhost
  become: true

  tasks:
    - name: Get current user
      set_fact:
        current_user: "{{ lookup('env', 'USER') | default(ansible_user) }}"

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add the user to the docker group
      user:
        name: "{{ current_user }}"
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
