name: CICD-GitHub-Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: us-east-1

      - name: Check for existing AMI and Install Packer if not found
        id: ami_and_packer
        run: |
          ami_id=$(aws ec2 describe-images --filters "Name=name,Values=telerik-demo-ami" --query 'Images[0].ImageId' --output text || echo "not_found")
          echo "Found AMI: $ami_id"
          echo "::set-output name=ami_id::$ami_id"

          if [ "$ami_id" == "None" ]; then
           wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
           echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
           sudo apt update && sudo apt install packer
          fi

      - name: Build AMI using Packer
        if: steps.ami_and_packer.outputs.ami_id == 'not_found'
        run: |
          cd packer
          packer build -var 'aws_access_key={{ env.AWS_ACCESS_KEY_ID }}' -var 'aws_secret_key={{ env.AWS_SECRET_ACCESS_KEY }}' packer.pkr.hcl

      # ... (rest of your steps)

      - name: Copy tfstate, tfplan, and SSH key to the created S3 Bucket
        run: |
          cd terraform
          aws s3 cp terraform.tfstate s3://devops-tfm-s3-bucket-us-east-1a/terraform.tfstate
          aws s3 cp MyAWSKey.pem s3://devops-tfm-s3-bucket-us-east-1a/MyAWSKey.pem
          aws s3 cp tfplan s3://devops-tfm-s3-bucket-us-east-1a/tfplan
