name: Terraform-GitHub-Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install Checkov with pip
        run: pip install checkov

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Checkov Scan
        id: checkov
        run: |
          cd terraform
          checkov -d .
      - name: Check Checkov Results
        if: ${{ steps.checkov.outputs.returncode == 1 }}
        run: echo "Checkov managed to find some Vulnerabilities, proceed at your own risk"
        #run: exit 1

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan -out=tfplan
          
      - name: Terraform Apply
        id: apply
        run: |
          cd terraform
          terraform apply --auto-approve tfplan
